server:
  port: 8761
  ssl:
    enabled: false  # Enable this and provide keystore details for production

spring:
  application:
    name: eureka
  security:
    user:
      name: admin
      password: ${EUREKA_PASSWORD:strongpassword}
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
    cache:
      period: 3600
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false  # Disable in development, enable in production
    renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  dashboard:
    enabled: true
    path: /dashboard
    template-location: classpath:/templates/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO