server:
  port: ${SERVER_PORT:8761}
  address: 0.0.0.0  # Bind to all network interfaces
  ssl:
    enabled: false  # Enable this and provide keystore details for production
  forward-headers-strategy: framework

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: ${EUREKA_PASSWORD:strongpassword}
  mvc:
    static-path-pattern: /**
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
    pathmatch:
      matching-strategy: ant_path_matcher
  resources:
    static-locations: classpath:/static/
    cache:
      period: 3600
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false  # Disable in development, enable in production
    renewalPercentThreshold: 0.85
    response-cache-update-interval-ms: 1000
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
  dashboard:
    enabled: true
    path: /dashboard
    template-location: classpath:/templates/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO